import numpy
A = numpy.array([[1, 2], [4, 3]])
B = numpy.array([[2, 2], [5, 6]])
print("Matrix :")
print(A)
print(B)
print("Add :")
print(numpy.add(A, B))
print("Sub :")
print(numpy.subtract(A, B))
print("Mul :")
print(numpy.multiply(A, B))
print("Transpose of A and B :")
print(A.T)
print(B.T)
print("Inverse of matrix :")
print(numpy.linalg.inv(A))
print(numpy.linalg.inv(B))
